server:
  port: 80
spring:
  application:
    name: cloud-hystrix-consumer-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    com.cloud.service.OpenFeignService: debug
feign:
  hystrix:
    enabled: true