server:
  port: 8001
spring:
  application:
    name: cloud-producer-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/testspringcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1477112645

mybatis:
  type-aliases-package: com.cloud.entity
  mapper-locations: classpath:mapper/*.xml