server:
  port: 80
spring:
  application:
    name: cloud-consumer-service
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka